//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accion_de_negocio_por_tipo_transaccion
    {
        public int id { get; set; }
        public int id_tipo_transaccion { get; set; }
        public int id_accion_de_negocio { get; set; }
        public bool valor { get; set; }
    
        public virtual Accion_de_negocio Accion_de_negocio { get; set; }
        public virtual Tipo_transaccion Tipo_transaccion { get; set; }
    }
}
