//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor_negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actor_negocio()
        {
            this.Actor_negocio1 = new HashSet<Actor_negocio>();
            this.Actor_negocio_por_transaccion = new HashSet<Actor_negocio_por_transaccion>();
            this.Actor_negocio_rol = new HashSet<Actor_negocio_rol>();
            this.Estado_cuota = new HashSet<Estado_cuota>();
            this.Estado_transaccion = new HashSet<Estado_transaccion>();
            this.Evento_transaccion = new HashSet<Evento_transaccion>();
            this.Existencia = new HashSet<Existencia>();
            this.Parametro_actor_negocio = new HashSet<Parametro_actor_negocio>();
            this.Precio = new HashSet<Precio>();
            this.Precio1 = new HashSet<Precio>();
            this.Transaccion = new HashSet<Transaccion>();
            this.Transaccion1 = new HashSet<Transaccion>();
            this.Transaccion2 = new HashSet<Transaccion>();
            this.Transaccion3 = new HashSet<Transaccion>();
            this.Transaccion4 = new HashSet<Transaccion>();
            this.Vinculo_Actor_Negocio = new HashSet<Vinculo_Actor_Negocio>();
            this.Vinculo_Actor_Negocio1 = new HashSet<Vinculo_Actor_Negocio>();
            this.Serie_comprobante = new HashSet<Serie_comprobante>();
        }
    
        public int id { get; set; }
        public int id_actor { get; set; }
        public int id_rol { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string codigo_negocio { get; set; }
        public bool es_vigente { get; set; }
        public string id_usuario { get; set; }
        public Nullable<int> id_actor_negocio_padre { get; set; }
        public string extension_json { get; set; }
        public Nullable<int> id_detalle_maestro_multiproposito { get; set; }
        public bool indicador1 { get; set; }
        public Nullable<int> id_concepto_negocio { get; set; }
    
        public virtual Actor Actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio> Actor_negocio1 { get; set; }
        public virtual Actor_negocio Actor_negocio2 { get; set; }
        public virtual Concepto_negocio Concepto_negocio { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio_por_transaccion> Actor_negocio_por_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio_rol> Actor_negocio_rol { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_cuota> Estado_cuota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_transaccion> Estado_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento_transaccion> Evento_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Existencia> Existencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_actor_negocio> Parametro_actor_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vinculo_Actor_Negocio> Vinculo_Actor_Negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vinculo_Actor_Negocio> Vinculo_Actor_Negocio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serie_comprobante> Serie_comprobante { get; set; }
    }
}
