//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atributo_actor
    {
        public long id { get; set; }
        public int id_actor { get; set; }
        public int id_atributo { get; set; }
        public string valor { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Atributo Atributo { get; set; }
    }
}
