//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comprobante()
        {
            this.Cuota = new HashSet<Cuota>();
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public long id { get; set; }
        public int id_tipo_comprobante { get; set; }
        public Nullable<int> id_serie_comprobante { get; set; }
        public int numero { get; set; }
        public bool es_valido { get; set; }
        public string numero_serie { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        public virtual Serie_comprobante Serie_comprobante { get; set; }
    }
}
