//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto_negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concepto_negocio()
        {
            this.Actor_negocio = new HashSet<Actor_negocio>();
            this.Concepto_negocio1 = new HashSet<Concepto_negocio>();
            this.Valor_caracteristica_concepto_negocio = new HashSet<Valor_caracteristica_concepto_negocio>();
            this.Concepto_negocio_rol = new HashSet<Concepto_negocio_rol>();
            this.Existencia = new HashSet<Existencia>();
            this.Mapeo_cuenta_contable_concepto = new HashSet<Mapeo_cuenta_contable_concepto>();
            this.Parametro_concepto_negocio = new HashSet<Parametro_concepto_negocio>();
            this.Precio = new HashSet<Precio>();
            this.Precio1 = new HashSet<Precio>();
            this.Detalle_transaccion = new HashSet<Detalle_transaccion>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string codigo_barra { get; set; }
        public string nombre { get; set; }
        public string sufijo { get; set; }
        public string propiedades { get; set; }
        public int id_unidad_medida_primaria { get; set; }
        public Nullable<int> id_presentacion { get; set; }
        public decimal contenido { get; set; }
        public Nullable<int> id_unidad_medida_contenido { get; set; }
        public Nullable<int> id_sub_contenido { get; set; }
        public Nullable<long> id_foto { get; set; }
        public bool es_vigente { get; set; }
        public int id_unidad_medida_secundaria { get; set; }
        public byte[] codigo_barra_imagen { get; set; }
        public int id_concepto_basico { get; set; }
        public decimal stock_minimo { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public string codigo_negocio1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio> Actor_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio> Concepto_negocio1 { get; set; }
        public virtual Concepto_negocio Concepto_negocio2 { get; set; }
        public virtual Foto Foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_caracteristica_concepto_negocio> Valor_caracteristica_concepto_negocio { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Detalle_maestro Detalle_maestro1 { get; set; }
        public virtual Detalle_maestro Detalle_maestro2 { get; set; }
        public virtual Detalle_maestro Detalle_maestro3 { get; set; }
        public virtual Detalle_maestro Detalle_maestro4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio_rol> Concepto_negocio_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Existencia> Existencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapeo_cuenta_contable_concepto> Mapeo_cuenta_contable_concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_concepto_negocio> Parametro_concepto_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_transaccion> Detalle_transaccion { get; set; }
    }
}
