//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta_contable()
        {
            this.Detalle_transaccion = new HashSet<Detalle_transaccion>();
            this.Mapeo_cuenta_contable_concepto = new HashSet<Mapeo_cuenta_contable_concepto>();
        }
    
        public int id { get; set; }
        public int id_plan { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string tipo_cuenta { get; set; }
        public Nullable<int> nivel_saldo { get; set; }
        public Nullable<int> id_tipo_anexo { get; set; }
        public Nullable<int> id_tipo_anexo_referencia { get; set; }
        public Nullable<int> tasa { get; set; }
        public Nullable<bool> requiere_centro_costo { get; set; }
        public Nullable<bool> requiere_documento_referencia { get; set; }
        public Nullable<bool> requiere_fecha_vencimiento { get; set; }
        public Nullable<bool> requiere_area { get; set; }
        public Nullable<bool> requiere_cuenta_ajuste { get; set; }
        public Nullable<bool> requiere_conciliacion_bancos { get; set; }
        public Nullable<bool> requiere_documento_referencia2 { get; set; }
        public Nullable<bool> requiere_tipo_medio_pago { get; set; }
        public Nullable<bool> registro_manual { get; set; }
        public Nullable<int> id_moneda_referencia { get; set; }
        public Nullable<int> id_cuenta_cargo { get; set; }
        public Nullable<int> id_cuenta_abono { get; set; }
    
        public virtual Plan_contable Plan_contable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_transaccion> Detalle_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapeo_cuenta_contable_concepto> Mapeo_cuenta_contable_concepto { get; set; }
    }
}
