//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuota()
        {
            this.Pago_cuota = new HashSet<Pago_cuota>();
            this.Estado_cuota = new HashSet<Estado_cuota>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string codigo_unico_banco { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public decimal total { get; set; }
        public decimal capital { get; set; }
        public decimal interes { get; set; }
        public long id_transaccion { get; set; }
        public bool letra_cambio { get; set; }
        public string comentario { get; set; }
        public bool cuota_inicial { get; set; }
        public Nullable<long> id_comprobante { get; set; }
        public Nullable<int> id_banco { get; set; }
        public bool por_cobrar { get; set; }
        public decimal pago_a_cuenta { get; set; }
        public decimal revocado { get; set; }
        public decimal saldo { get; set; }
    
        public virtual Comprobante Comprobante { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Transaccion Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_cuota> Pago_cuota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_cuota> Estado_cuota { get; set; }
    }
}
