//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_maestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detalle_maestro()
        {
            this.Accion_por_estado = new HashSet<Accion_por_estado>();
            this.Accion_por_estado1 = new HashSet<Accion_por_estado>();
            this.Accion_por_rol = new HashSet<Accion_por_rol>();
            this.Accion_por_rol1 = new HashSet<Accion_por_rol>();
            this.Actor = new HashSet<Actor>();
            this.Actor1 = new HashSet<Actor>();
            this.Actor2 = new HashSet<Actor>();
            this.Actor_negocio = new HashSet<Actor_negocio>();
            this.Actor_negocio_por_transaccion = new HashSet<Actor_negocio_por_transaccion>();
            this.Caracteristica_concepto = new HashSet<Caracteristica_concepto>();
            this.Caracteristica_concepto1 = new HashSet<Caracteristica_concepto>();
            this.Categoria_concepto = new HashSet<Categoria_concepto>();
            this.Categoria_concepto1 = new HashSet<Categoria_concepto>();
            this.Comprobante = new HashSet<Comprobante>();
            this.Concepto_negocio = new HashSet<Concepto_negocio>();
            this.Concepto_negocio1 = new HashSet<Concepto_negocio>();
            this.Concepto_negocio2 = new HashSet<Concepto_negocio>();
            this.Concepto_negocio3 = new HashSet<Concepto_negocio>();
            this.Concepto_negocio4 = new HashSet<Concepto_negocio>();
            this.Cuota = new HashSet<Cuota>();
            this.Detalle_detalle_maestro = new HashSet<Detalle_detalle_maestro>();
            this.Detalle_detalle_maestro1 = new HashSet<Detalle_detalle_maestro>();
            this.Turno = new HashSet<Turno>();
            this.Direccion = new HashSet<Direccion>();
            this.Direccion1 = new HashSet<Direccion>();
            this.Direccion2 = new HashSet<Direccion>();
            this.Direccion3 = new HashSet<Direccion>();
            this.Estado_cuota = new HashSet<Estado_cuota>();
            this.Estado_transaccion = new HashSet<Estado_transaccion>();
            this.Evento_transaccion = new HashSet<Evento_transaccion>();
            this.Marca_concepto = new HashSet<Marca_concepto>();
            this.Marca_concepto1 = new HashSet<Marca_concepto>();
            this.Parametro_actor_negocio = new HashSet<Parametro_actor_negocio>();
            this.Parametro_actor_negocio1 = new HashSet<Parametro_actor_negocio>();
            this.Parametro_concepto_negocio = new HashSet<Parametro_concepto_negocio>();
            this.Parametro_concepto_negocio1 = new HashSet<Parametro_concepto_negocio>();
            this.Parametro_transaccion = new HashSet<Parametro_transaccion>();
            this.Parametro_por_rol = new HashSet<Parametro_por_rol>();
            this.Parametro_por_unidad_negocio = new HashSet<Parametro_por_unidad_negocio>();
            this.Parametro_por_unidad_negocio1 = new HashSet<Parametro_por_unidad_negocio>();
            this.Precio = new HashSet<Precio>();
            this.Precio1 = new HashSet<Precio>();
            this.Precio2 = new HashSet<Precio>();
            this.Precio3 = new HashSet<Precio>();
            this.Rol_por_unidad_negocio = new HashSet<Rol_por_unidad_negocio>();
            this.Serie_comprobante = new HashSet<Serie_comprobante>();
            this.Tipo_cambio = new HashSet<Tipo_cambio>();
            this.Tipo_transaccion_tipo_comprobante = new HashSet<Tipo_transaccion_tipo_comprobante>();
            this.Transaccion = new HashSet<Transaccion>();
            this.Transaccion1 = new HashSet<Transaccion>();
            this.Transaccion2 = new HashSet<Transaccion>();
            this.Traza_pago = new HashSet<Traza_pago>();
            this.Traza_pago1 = new HashSet<Traza_pago>();
            this.Traza_pago2 = new HashSet<Traza_pago>();
            this.Valor_caracteristica_concepto = new HashSet<Valor_caracteristica_concepto>();
            this.Valor_caracteristica = new HashSet<Valor_caracteristica>();
            this.Valor_detalle_maestro_detalle_transaccion = new HashSet<Valor_detalle_maestro_detalle_transaccion>();
        }
    
        public int id { get; set; }
        public int id_maestro { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<long> id_foto { get; set; }
        public bool es_vigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_por_estado> Accion_por_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_por_estado> Accion_por_estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_por_rol> Accion_por_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_por_rol> Accion_por_rol1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio> Actor_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio_por_transaccion> Actor_negocio_por_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caracteristica_concepto> Caracteristica_concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caracteristica_concepto> Caracteristica_concepto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria_concepto> Categoria_concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria_concepto> Categoria_concepto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio> Concepto_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio> Concepto_negocio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio> Concepto_negocio2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio> Concepto_negocio3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto_negocio> Concepto_negocio4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_detalle_maestro> Detalle_detalle_maestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_detalle_maestro> Detalle_detalle_maestro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turno { get; set; }
        public virtual Foto Foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_cuota> Estado_cuota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_transaccion> Estado_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento_transaccion> Evento_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marca_concepto> Marca_concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marca_concepto> Marca_concepto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_actor_negocio> Parametro_actor_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_actor_negocio> Parametro_actor_negocio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_concepto_negocio> Parametro_concepto_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_concepto_negocio> Parametro_concepto_negocio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_transaccion> Parametro_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_por_rol> Parametro_por_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_por_unidad_negocio> Parametro_por_unidad_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_por_unidad_negocio> Parametro_por_unidad_negocio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol_por_unidad_negocio> Rol_por_unidad_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serie_comprobante> Serie_comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_cambio> Tipo_cambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_transaccion_tipo_comprobante> Tipo_transaccion_tipo_comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traza_pago> Traza_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traza_pago> Traza_pago1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traza_pago> Traza_pago2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_caracteristica_concepto> Valor_caracteristica_concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_caracteristica> Valor_caracteristica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_detalle_maestro_detalle_transaccion> Valor_detalle_maestro_detalle_transaccion { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
