//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int id { get; set; }
        public int id_tipo_direccion { get; set; }
        public int id_nacion { get; set; }
        public int id_ubigeo { get; set; }
        public string detalle { get; set; }
        public int id_actor { get; set; }
        public Nullable<int> id_tipo_via { get; set; }
        public Nullable<int> id_tipo_zona { get; set; }
        public bool es_principal { get; set; }
        public bool es_activo { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Detalle_maestro Detalle_maestro1 { get; set; }
        public virtual Detalle_maestro Detalle_maestro2 { get; set; }
        public virtual Detalle_maestro Detalle_maestro3 { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
