//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_identidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento_identidad()
        {
            this.Documento_identidad_por_tipo_actor = new HashSet<Documento_identidad_por_tipo_actor>();
        }
    
        public int id { get; set; }
        public string nombre_corto { get; set; }
        public string nombre_largo { get; set; }
        public int longitud { get; set; }
        public string mascara { get; set; }
        public string detalle_legal { get; set; }
        public bool es_primario { get; set; }
        public bool es_para_negocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento_identidad_por_tipo_actor> Documento_identidad_por_tipo_actor { get; set; }
    }
}
