//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_identidad_por_tipo_actor
    {
        public int id { get; set; }
        public int identityDocumentId { get; set; }
        public int actorTypeId { get; set; }
    
        public virtual Documento_identidad Documento_identidad { get; set; }
        public virtual Tipo_actor Tipo_actor { get; set; }
    }
}
