//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existencia
    {
        public int id { get; set; }
        public int id_punto_atencion { get; set; }
        public int id_concepto_negocio { get; set; }
        public decimal existencia1 { get; set; }
        public byte[] version_fila { get; set; }
    
        public virtual Actor_negocio Actor_negocio { get; set; }
        public virtual Concepto_negocio Concepto_negocio { get; set; }
    }
}
