//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapeo_cuenta_contable_concepto
    {
        public int id { get; set; }
        public int id_concepto_negocio { get; set; }
        public int id_cuenta_contable { get; set; }
        public bool es_vigente { get; set; }
    
        public virtual Concepto_negocio Concepto_negocio { get; set; }
        public virtual Cuenta_contable Cuenta_contable { get; set; }
    }
}
