//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_aplicacion
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string controller { get; set; }
        public string accion { get; set; }
        public string icono { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> id_padre { get; set; }
        public Nullable<bool> es_padre { get; set; }
    }
}
