//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_cuota
    {
        public int id { get; set; }
        public int id_cuota { get; set; }
        public long id_transaccion { get; set; }
        public decimal importe { get; set; }
    
        public virtual Cuota Cuota { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
