//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Precio()
        {
            this.Detalle_transaccion = new HashSet<Detalle_transaccion>();
        }
    
        public int id { get; set; }
        public int id_actor_negocio { get; set; }
        public int id_unidad_negocio { get; set; }
        public int id_concepto_negocio { get; set; }
        public decimal valor { get; set; }
        public int id_tarifa_d { get; set; }
        public int id_moneda { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public bool indicador_multiproposito { get; set; }
        public bool es_vigente { get; set; }
        public Nullable<bool> porcentaje { get; set; }
        public Nullable<int> cantidad_minima { get; set; }
        public Nullable<int> cantidad_maxima { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public Nullable<int> id_concepto_negocio_referencial { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public string descripcion { get; set; }
    
        public virtual Actor_negocio Actor_negocio { get; set; }
        public virtual Actor_negocio Actor_negocio1 { get; set; }
        public virtual Concepto_negocio Concepto_negocio { get; set; }
        public virtual Concepto_negocio Concepto_negocio1 { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Detalle_maestro Detalle_maestro1 { get; set; }
        public virtual Detalle_maestro Detalle_maestro2 { get; set; }
        public virtual Detalle_maestro Detalle_maestro3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_transaccion> Detalle_transaccion { get; set; }
    }
}
