//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referencia_detalle_transaccion
    {
        public int id { get; set; }
        public long id_detalle { get; set; }
        public long id_transaccion { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual Detalle_transaccion Detalle_transaccion { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
