//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_por_unidad_negocio
    {
        public int id { get; set; }
        public int id_rol { get; set; }
        public int id_unidad_negocio { get; set; }
        public int numero_orden { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
