//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie_comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serie_comprobante()
        {
            this.Comprobante = new HashSet<Comprobante>();
        }
    
        public int id { get; set; }
        public string numero { get; set; }
        public int id_propietario { get; set; }
        public bool es_vigente { get; set; }
        public int id_tipo_comprobante { get; set; }
        public int proximo_numero { get; set; }
        public bool es_autonumerable { get; set; }
        public int id_modelo_comprobante { get; set; }
        public byte[] version_fila { get; set; }
    
        public virtual Actor_negocio Actor_negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual VoucherModel VoucherModel { get; set; }
    }
}
