//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_transaccion()
        {
            this.Accion_de_negocio_por_tipo_transaccion = new HashSet<Accion_de_negocio_por_tipo_transaccion>();
            this.Accion_por_estado = new HashSet<Accion_por_estado>();
            this.Accion_por_rol = new HashSet<Accion_por_rol>();
            this.Transaccion = new HashSet<Transaccion>();
            this.Tipo_transaccion1 = new HashSet<Tipo_transaccion>();
            this.Tipo_transaccion_tipo_comprobante = new HashSet<Tipo_transaccion_tipo_comprobante>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int acciones_de_entrada_o_salida { get; set; }
        public Nullable<int> id_tipo_transaccion_padre { get; set; }
        public string cuenta { get; set; }
        public Nullable<int> id_tipo_comprobante_defecto { get; set; }
        public string nombre_corto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_de_negocio_por_tipo_transaccion> Accion_de_negocio_por_tipo_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_por_estado> Accion_por_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accion_por_rol> Accion_por_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_transaccion> Tipo_transaccion1 { get; set; }
        public virtual Tipo_transaccion Tipo_transaccion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_transaccion_tipo_comprobante> Tipo_transaccion_tipo_comprobante { get; set; }
    }
}
