//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_cambio
    {
        public int id { get; set; }
        public int idMoneda { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal valorCompra { get; set; }
        public decimal valorVenta { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
    }
}
