//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_actor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_actor()
        {
            this.Actor = new HashSet<Actor>();
            this.Documento_identidad_por_tipo_actor = new HashSet<Documento_identidad_por_tipo_actor>();
            this.Rol_por_tipo_actor = new HashSet<Rol_por_tipo_actor>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string primera_denominacion { get; set; }
        public string segunda_denominacion { get; set; }
        public string denominacion_de_clase { get; set; }
        public string tercera_denominacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento_identidad_por_tipo_actor> Documento_identidad_por_tipo_actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol_por_tipo_actor> Rol_por_tipo_actor { get; set; }
    }
}
