//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_transaccion_tipo_comprobante
    {
        public int id { get; set; }
        public int id_tipo_transaccion { get; set; }
        public int id_tipo_comprobante { get; set; }
        public bool es_propio { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Tipo_transaccion Tipo_transaccion { get; set; }
    }
}
