//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Actor_negocio_por_transaccion = new HashSet<Actor_negocio_por_transaccion>();
            this.Cuota = new HashSet<Cuota>();
            this.Detalle_transaccion = new HashSet<Detalle_transaccion>();
            this.Estado_transaccion = new HashSet<Estado_transaccion>();
            this.Evento_transaccion = new HashSet<Evento_transaccion>();
            this.Pago_cuota = new HashSet<Pago_cuota>();
            this.Parametro_transaccion = new HashSet<Parametro_transaccion>();
            this.Referencia_detalle_transaccion = new HashSet<Referencia_detalle_transaccion>();
            this.Transaccion1 = new HashSet<Transaccion>();
            this.Transaccion11 = new HashSet<Transaccion>();
            this.Traza_pago = new HashSet<Traza_pago>();
        }
    
        public long id { get; set; }
        public string codigo { get; set; }
        public Nullable<long> id_transaccion_padre { get; set; }
        public System.DateTime fecha_registro_sistema { get; set; }
        public int id_tipo_transaccion { get; set; }
        public int id_unidad_negocio { get; set; }
        public bool es_concreta { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public long id_comprobante { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha_registro_contable { get; set; }
        public int id_empleado { get; set; }
        public decimal importe_total { get; set; }
        public int id_actor_negocio_interno { get; set; }
        public int id_moneda { get; set; }
        public decimal tipo_cambio { get; set; }
        public Nullable<long> id_transaccion_referencia { get; set; }
        public int id_actor_negocio_externo { get; set; }
        public Nullable<int> id_estado_actual { get; set; }
        public Nullable<int> id_actor_negocio_externo1 { get; set; }
        public int enum1 { get; set; }
        public bool indicador1 { get; set; }
        public bool indicador2 { get; set; }
        public decimal importe1 { get; set; }
        public decimal importe2 { get; set; }
        public decimal importe3 { get; set; }
        public decimal importe4 { get; set; }
        public decimal importe5 { get; set; }
        public decimal importe6 { get; set; }
        public decimal importe7 { get; set; }
        public decimal importe8 { get; set; }
        public decimal importe9 { get; set; }
        public decimal importe10 { get; set; }
        public decimal importe11 { get; set; }
        public decimal importe12 { get; set; }
        public Nullable<int> id_actor_negocio_interno1 { get; set; }
        public decimal cantidad1 { get; set; }
        public decimal cantidad2 { get; set; }
        public decimal cantidad3 { get; set; }
        public decimal cantidad4 { get; set; }
        public string informacion { get; set; }
        public Nullable<int> id_evento_referencia { get; set; }
        public Nullable<int> id_estado_actual_1 { get; set; }
    
        public virtual Actor_negocio Actor_negocio { get; set; }
        public virtual Actor_negocio Actor_negocio1 { get; set; }
        public virtual Actor_negocio Actor_negocio2 { get; set; }
        public virtual Actor_negocio Actor_negocio3 { get; set; }
        public virtual Actor_negocio Actor_negocio4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor_negocio_por_transaccion> Actor_negocio_por_transaccion { get; set; }
        public virtual Comprobante Comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuota { get; set; }
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Detalle_maestro Detalle_maestro2 { get; set; }
        public virtual Detalle_maestro Detalle_maestro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_transaccion> Detalle_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_transaccion> Estado_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento_transaccion> Evento_transaccion { get; set; }
        public virtual Evento_transaccion Evento_transaccion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_cuota> Pago_cuota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro_transaccion> Parametro_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencia_detalle_transaccion> Referencia_detalle_transaccion { get; set; }
        public virtual Tipo_transaccion Tipo_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion1 { get; set; }
        public virtual Transaccion Transaccion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion11 { get; set; }
        public virtual Transaccion Transaccion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traza_pago> Traza_pago { get; set; }
    }
}
