//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traza_pago
    {
        public int id { get; set; }
        public long id_transaccion { get; set; }
        public int id_medio_pago { get; set; }
        public string traza { get; set; }
        public int id_entidad_bancaria { get; set; }
        public Nullable<int> id_tipo_operador { get; set; }
        public string extension_json { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        public virtual Detalle_maestro Detalle_maestro1 { get; set; }
        public virtual Detalle_maestro Detalle_maestro2 { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
