//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public decimal duracion_horas { get; set; }
        public int id_tipo { get; set; }
        public string extension_json { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
    }
}
