//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_caracteristica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valor_caracteristica()
        {
            this.Valor_caracteristica_concepto = new HashSet<Valor_caracteristica_concepto>();
            this.Valor_caracteristica_concepto_negocio = new HashSet<Valor_caracteristica_concepto_negocio>();
        }
    
        public int id { get; set; }
        public int id_caracteristica { get; set; }
        public string valor { get; set; }
        public string valor_1 { get; set; }
    
        public virtual Detalle_maestro Detalle_maestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_caracteristica_concepto> Valor_caracteristica_concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_caracteristica_concepto_negocio> Valor_caracteristica_concepto_negocio { get; set; }
    }
}
