//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoucherModel()
        {
            this.Serie_comprobante = new HashSet<Serie_comprobante>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int linesNumber { get; set; }
        public int lineWidth { get; set; }
        public int lineHeight { get; set; }
        public int amountDetailWidth { get; set; }
        public int unitPriceDetailWidth { get; set; }
        public int totalMoneyDetailWidth { get; set; }
        public int headerLinesNumber { get; set; }
        public int detailLinesNumber { get; set; }
        public int resumeLinesNumber { get; set; }
        public int footerLinesNumber { get; set; }
        public string fontType { get; set; }
        public int fontSize { get; set; }
        public int columnPadding { get; set; }
        public int leftMargin { get; set; }
        public int upMargin { get; set; }
        public int pageHeight { get; set; }
        public int pageWidth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serie_comprobante> Serie_comprobante { get; set; }
    }
}
