//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades.EFactura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturacionEntities : DbContext
    {
        public FacturacionEntities()
            : base("name=FacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Binario> Binario { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Envio> Envio { get; set; }
        public virtual DbSet<EnvioDocumento> EnvioDocumento { get; set; }
        public virtual DbSet<ProgramacionEnvio> ProgramacionEnvio { get; set; }
    }
}
