//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades.EFactura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Envio()
        {
            this.EnvioDocumento = new HashSet<EnvioDocumento>();
        }
    
        public long id { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public string tipoEnvio { get; set; }
        public long idBinarioEnvio { get; set; }
        public Nullable<long> idBinarioRespuesta { get; set; }
        public int estado { get; set; }
        public string codigoRespuesta { get; set; }
        public string observacion { get; set; }
        public string identificadorEnvio { get; set; }
        public string numeroTicket { get; set; }
        public int modoEnvio { get; set; }
    
        public virtual Binario Binario { get; set; }
        public virtual Binario Binario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioDocumento> EnvioDocumento { get; set; }
    }
}
