//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades.EFactura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioDocumento
    {
        public long id { get; set; }
        public long idDocumento { get; set; }
        public long idEnvio { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Envio Envio { get; set; }
    }
}
