//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsp.Sigescom.Modelo.Entidades.EFactura
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionEnvio
    {
        public long id { get; set; }
        public string diaSemana { get; set; }
        public System.TimeSpan horaInicial { get; set; }
        public int duracion { get; set; }
        public string tipoEnvioProgramado { get; set; }
        public Nullable<long> idUsuario { get; set; }
    }
}
